/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthPathnameRouteImport } from './routes/auth/$pathname'
import { Route as legalTosRouteImport } from './routes/(legal)/tos'
import { Route as legalPrivacyPolicyRouteImport } from './routes/(legal)/privacy-policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const legalTosRoute = legalTosRouteImport.update({
  id: '/(legal)/tos',
  path: '/tos',
  getParentRoute: () => rootRouteImport,
} as any)
const legalPrivacyPolicyRoute = legalPrivacyPolicyRouteImport.update({
  id: '/(legal)/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof legalPrivacyPolicyRoute
  '/tos': typeof legalTosRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof legalPrivacyPolicyRoute
  '/tos': typeof legalTosRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(legal)/privacy-policy': typeof legalPrivacyPolicyRoute
  '/(legal)/tos': typeof legalTosRoute
  '/auth/$pathname': typeof AuthPathnameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/privacy-policy' | '/tos' | '/auth/$pathname'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/privacy-policy' | '/tos' | '/auth/$pathname'
  id:
    | '__root__'
    | '/'
    | '/(legal)/privacy-policy'
    | '/(legal)/tos'
    | '/auth/$pathname'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  legalPrivacyPolicyRoute: typeof legalPrivacyPolicyRoute
  legalTosRoute: typeof legalTosRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/tos': {
      id: '/(legal)/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof legalTosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(legal)/privacy-policy': {
      id: '/(legal)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof legalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  legalPrivacyPolicyRoute: legalPrivacyPolicyRoute,
  legalTosRoute: legalTosRoute,
  AuthPathnameRoute: AuthPathnameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
